# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Currency.create(country: "Albania Lek", code: "ALL", symbol: "Lek")
Currency.create(country: "Afghanistan Afghani", code: "AFN", symbol: "؋")
Currency.create(country: "Argentina Peso", code: "ARS", symbol: "$")
Currency.create(country: "Aruba Guilder", code: "AWG", symbol: "ƒ")
Currency.create(country: "Australia Dollar", code: "AUD", symbol: "$")
Currency.create(country: "Azerbaijan New Manat", code: "AZN", symbol: "ман")
Currency.create(country: "Bahamas Dollar", code: "BSD", symbol: "$")
Currency.create(country: "Barbados Dollar", code: "BBD", symbol: "$")
Currency.create(country: "Belarus Ruble", code: "BYR", symbol: "p.")
Currency.create(country: "Belize Dollar", code: "BZD", symbol: "BZ$")
Currency.create(country: "Bermuda Dollar", code: "BMD", symbol: "$")
Currency.create(country: "Bolivia Boliviano", code: "BOB", symbol: "$b")
Currency.create(country: "Bosnia and Herzegovina Convertible Marka", code: "BAM", symbol: "KM")
Currency.create(country: "Botswana Pula", code: "BWP", symbol: "P")
Currency.create(country: "Bulgaria Lev", code: "BGN", symbol: "лв")
Currency.create(country: "Brazil Real", code: "BRL", symbol: "R$")
Currency.create(country: "Brunei Darussalam Dollar", code: "BND", symbol: "$")
Currency.create(country: "Cambodia Riel", code: "KHR", symbol: "៛")
Currency.create(country: "Canada Dollar", code: "CAD", symbol: "$")
Currency.create(country: "Cayman Islands Dollar", code: "KYD", symbol: "$")
Currency.create(country: "Chile Peso", code: "CLP", symbol: "$")
Currency.create(country: "China Yuan Renminbi", code: "CNY", symbol: "¥")
Currency.create(country: "Colombia Peso", code: "COP", symbol: "$")
Currency.create(country: "Costa Rica Colon", code: "CRC", symbol: "₡")
Currency.create(country: "Croatia Kuna", code: "HRK", symbol: "kn")
Currency.create(country: "Cuba Peso", code: "CUP", symbol: "₱")
Currency.create(country: "Czech Republic Koruna", code: "CZK", symbol: "Kč")
Currency.create(country: "Denmark Krone", code: "DKK", symbol: "kr")
Currency.create(country: "Dominican Republic Peso", code: "DOP", symbol: "RD$")
Currency.create(country: "East Caribbean Dollar", code: "XCD", symbol: "$")
Currency.create(country: "Egypt Pound", code: "EGP", symbol: "£")
Currency.create(country: "El Salvador Colon", code: "SVC", symbol: "$")
Currency.create(country: "Estonia Kroon", code: "EEK", symbol: "kr")
Currency.create(country: "Euro Member Countries", code: "EUR", symbol: "€")
Currency.create(country: "Falkland Islands (Malvinas) Pound", code: "FKP", symbol: "£")
Currency.create(country: "Fiji Dollar", code: "FJD", symbol: "$")
Currency.create(country: "Gibraltar Pound", code: "GIP", symbol: "£")
Currency.create(country: "Guatemala Quetzal", code: "GTQ", symbol: "Q")
Currency.create(country: "Guernsey Pound", code: "GGP", symbol: "£")
Currency.create(country: "Guyana Dollar", code: "GYD", symbol: "$")
Currency.create(country: "Honduras Lempira", code: "HNL", symbol: "L")
Currency.create(country: "Hong Kong Dollar", code: "HKD", symbol: "$")
Currency.create(country: "Hungary Forint", code: "HUF", symbol: "Ft")
Currency.create(country: "Iceland Krona", code: "ISK", symbol: "kr")
Currency.create(country: "India Rupee", code: "INR", symbol: "")
Currency.create(country: "Indonesia Rupiah", code: "IDR", symbol: "Rp")
Currency.create(country: "Iran Rial", code: "IRR", symbol: "﷼")
Currency.create(country: "Isle of Man Pound", code: "IMP", symbol: "£")
Currency.create(country: "Israel Shekel", code: "ILS", symbol: "₪")
Currency.create(country: "Jamaica Dollar", code: "JMD", symbol: "J$")
Currency.create(country: "Japan Yen", code: "JPY", symbol: "¥")
Currency.create(country: "Jersey Pound", code: "JEP", symbol: "£")
Currency.create(country: "Kazakhstan Tenge", code: "KZT", symbol: "лв")
Currency.create(country: "Korea (North) Won", code: "KPW", symbol: "₩")
Currency.create(country: "Korea (South) Won", code: "KRW", symbol: "₩")
Currency.create(country: "Kyrgyzstan Som", code: "KGS", symbol: "лв")
Currency.create(country: "Laos Kip", code: "LAK", symbol: "₭")
Currency.create(country: "Latvia Lat", code: "LVL", symbol: "Ls")
Currency.create(country: "Lebanon Pound", code: "LBP", symbol: "£")
Currency.create(country: "Liberia Dollar", code: "LRD", symbol: "$")
Currency.create(country: "Lithuania Litas", code: "LTL", symbol: "Lt")
Currency.create(country: "Macedonia Denar", code: "MKD", symbol: "ден")
Currency.create(country: "Malaysia Ringgit", code: "MYR", symbol: "RM")
Currency.create(country: "Mauritius Rupee", code: "MUR", symbol: "₨")
Currency.create(country: "Mexico Peso", code: "MXN", symbol: "$")
Currency.create(country: "Mongolia Tughrik", code: "MNT", symbol: "₮")
Currency.create(country: "Mozambique Metical", code: "MZN", symbol: "MT")
Currency.create(country: "Namibia Dollar", code: "NAD", symbol: "$")
Currency.create(country: "Nepal Rupee", code: "NPR", symbol: "₨")
Currency.create(country: "Netherlands Antilles Guilder", code: "ANG", symbol: "ƒ")
Currency.create(country: "New Zealand Dollar", code: "NZD", symbol: "$")
Currency.create(country: "Nicaragua Cordoba", code: "NIO", symbol: "C$")
Currency.create(country: "Nigeria Naira", code: "NGN", symbol: "₦")
Currency.create(country: "Norway Krone", code: "NOK", symbol: "kr")
Currency.create(country: "Oman Rial", code: "OMR", symbol: "﷼")
Currency.create(country: "Pakistan Rupee", code: "PKR", symbol: "₨")
Currency.create(country: "Panama Balboa", code: "PAB", symbol: "B/.")
Currency.create(country: "Paraguay Guarani", code: "PYG", symbol: "Gs")
Currency.create(country: "Peru Nuevo Sol", code: "PEN", symbol: "S/.")
Currency.create(country: "Philippines Peso", code: "PHP", symbol: "₱")
Currency.create(country: "Poland Zloty", code: "PLN", symbol: "zł")
Currency.create(country: "Qatar Riyal", code: "QAR", symbol: "﷼")
Currency.create(country: "Romania New Leu", code: "RON", symbol: "lei")
Currency.create(country: "Russia Ruble", code: "RUB", symbol: "руб")
Currency.create(country: "Saint Helena Pound", code: "SHP", symbol: "£")
Currency.create(country: "Saudi Arabia Riyal", code: "SAR", symbol: "﷼")
Currency.create(country: "Serbia Dinar", code: "RSD", symbol: "Дин.")
Currency.create(country: "Seychelles Rupee", code: "SCR", symbol: "₨")
Currency.create(country: "Singapore Dollar", code: "SGD", symbol: "$")
Currency.create(country: "Solomon Islands Dollar", code: "SBD", symbol: "$")
Currency.create(country: "Somalia Shilling", code: "SOS", symbol: "S")
Currency.create(country: "South Africa Rand", code: "ZAR", symbol: "R")
Currency.create(country: "Sri Lanka Rupee", code: "LKR", symbol: "₨")
Currency.create(country: "Sweden Krona", code: "SEK", symbol: "kr")
Currency.create(country: "Switzerland Franc", code: "CHF", symbol: "CHF")
Currency.create(country: "Suriname Dollar", code: "SRD", symbol: "$")
Currency.create(country: "Syria Pound", code: "SYP", symbol: "£")
Currency.create(country: "Taiwan New Dollar", code: "TWD", symbol: "NT$")
Currency.create(country: "Thailand Baht", code: "THB", symbol: "฿")
Currency.create(country: "Trinidad and Tobago Dollar", code: "TTD", symbol: "TT$")
Currency.create(country: "Turkey Lira", code: "TRY", symbol: "₺")
Currency.create(country: "Ukraine Hryvnia", code: "UAH", symbol: "₴")
Currency.create(country: "United Kingdom Pound", code: "GBP", symbol: "£")
Currency.create(country: "United States Dollar", code: "USD", symbol: "$")
Currency.create(country: "Uruguay Peso", code: "UYU", symbol: "$U")
Currency.create(country: "Uzbekistan Som", code: "UZS", symbol: "лв")
Currency.create(country: "Venezuela Bolivar", code: "VEF", symbol: "Bs")
Currency.create(country: "Viet Nam Dong", code: "VND", symbol: "₫")
Currency.create(country: "Yemen Rial", code: "YER", symbol: "﷼")